### ISSUE TITLE
Latest Startup Bug

### ISSUE THREAD

**Issue by shillshocked** [PaulMcInnis/Better-Release-Radar#10]
PS C:\Programs\Better-Release-Radar> npm start -- --max-age-days 367 --region ""

> better-release-radar@2.3.0 start
> set NODE_OPTIONS=--no-warnings && ts-node ./src/main.ts 1 367

[12-29 12:55] [INFO]: Prompting user to authorize the app

  --------------------------------------------------
  Authorize your app by visiting this URL:
  https://accounts.spotify.com/authorize?client_id=EDITEDOUT&response_type=code&redirect_uri=http://localhost:8888/callback&scope=user-follow-read&state=random-state
  --------------------------------------------------

[12-29 12:55] [INFO]: Listening for Spotify authorization code on http://localhost:8888/callback
[12-29 12:55] [INFO]: Waiting for authorization before running main...
[12-29 12:55] [INFO]: Authorization code received:
Error exchanging authorization code: Error: ENOENT: no such file or directory, open 'C:\Programs\Better-Release-Radar\.cache\spotify_tokens.json'
    at Object.writeFileSync (node:fs:2344:20)
    at saveTokensToCache (C:\Programs\Better-Release-Radar\src\cache.ts:30:6)
    at exchangeAuthorizationCode (C:\Programs\Better-Release-Radar\src\auth.ts:28:22)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Server.<anonymous> (C:\Programs\Better-Release-Radar\src\auth.ts:93:9) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Programs\\Better-Release-Radar\\.cache\\spotify_tokens.json'
}
[12-29 12:55] [INFO]: Starting Better Release Radar...
[12-29 12:55] [INFO]: Prompting user to authorize the app

  --------------------------------------------------
  Authorize your app by visiting this URL:
  https://accounts.spotify.com/authorize?client_id=EDITEDOUT&response_type=code&redirect_uri=http://localhost:8888/callback&scope=user-follow-read&state=random-state
  --------------------------------------------------

[12-29 12:55] [INFO]: Listening for Spotify authorization code on http://localhost:8888/callback
[12-29 12:55] [INFO]: Total followed artists: 24224
[12-29 12:56] [ERROR]: Error fetching followed artists: An error occurred while communicating with Spotify's Web API.
Details: com.spotify.hermes.service.RequestTimeoutException: Request timed out: 062a625cd255d8-c783c8-bc41-1417-12cd14a2. Host: 0a841fa52a142a00000101f60000000000000025.ip.gae2.spotify.net.:5700.
[12-29 12:56] [ERROR]: Error running the script: An error occurred while communicating with Spotify's Web API.
Details: com.spotify.hermes.service.RequestTimeoutException: Request timed out: 062a625cd255d8-c783c8-bc41-1417-12cd14a2. Host: 0a841fa52a142a00000101f60000000000000025.ip.gae2.spotify.net.:5700.

**Comment by shillshocked** [comment]
I get the same error even with 9 days:

PS C:\Programs\Better-Release-Radar> npm start -- --max-age-days 9 --region ""

> better-release-radar@2.3.0 start
> set NODE_OPTIONS=--no-warnings && ts-node ./src/main.ts 1 9

[12-29 13:13] [INFO]: Prompting user to authorize the app

  --------------------------------------------------
  Authorize your app by visiting this URL:
  https://accounts.spotify.com/authorize?client_id=EDITEDOUT&response_type=code&redirect_uri=http://localhost:8888/callback&scope=user-follow-read&state=random-state
  --------------------------------------------------

[12-29 13:13] [INFO]: Listening for Spotify authorization code on http://localhost:8888/callback
[12-29 13:13] [INFO]: Waiting for authorization before running main...
[12-29 13:13] [INFO]: Authorization code received:
[12-29 13:13] [INFO]: Access token and refresh token set.
[12-29 13:13] [INFO]: Starting Better Release Radar...
[12-29 13:13] [INFO]: Using cached Spotify tokens.
[12-29 13:13] [INFO]: Total followed artists: 24224
[12-29 13:13] [ERROR]: Error fetching followed artists: An error occurred while communicating with Spotify's Web API.
Details: com.spotify.hermes.service.RequestTimeoutException: Request timed out: 062a6298e8d7b5-c59d5a-af72-9808-3441000b. Host: 0a84df9a2a142a00000101f6000005440000001a.ip.gae2.spotify.net.:5700.
[12-29 13:13] [ERROR]: Error running the script: An error occurred while communicating with Spotify's Web API.
Details: com.spotify.hermes.service.RequestTimeoutException: Request timed out: 062a6298e8d7b5-c59d5a-af72-9808-3441000b. Host: 0a84df9a2a142a00000101f6000005440000001a.ip.gae2.spotify.net.:5700.
PS C:\Programs\Better-Release-Radar>

**Comment by PaulMcInnis** [comment]
looks to me like it's related to caching? #7 

... that said your second log here, it has the token.

**Comment by PaulMcInnis** [comment]
this is a duplicate of #6 (api limitation)
