### ISSUE TITLE
Missing Spotify Token file

### ISSUE THREAD

**Issue by mike-lazarev** [PaulMcInnis/Better-Release-Radar#5]
When initially running the app, an error occurred that .cache folder and Spotify tokens did not exist. I manually created the folder and touched the file and it worked. 

```
[10-02 06:24] [ERROR]: Error running the script: ENOENT: no such file or directory, scandir '/home/redacted/projects/Better-Release-Radar/.cache'
[10-02 06:24] [INFO]: Listening for Spotify authorization code on http://localhost:8888/callback
[10-02 06:24] [INFO]: Authorization code received:
Error exchanging authorization code: Error: ENOENT: no such file or directory, open '/home/redacted/projects/Better-Release-Radar/.cache/spotify_tokens.json'
    at Object.writeFileSync (node:fs:2344:20)
    at saveTokensToCache (/home/redacted/projects/Better-Release-Radar/src/cache.ts:30:6)
    at exchangeAuthorizationCode (/home/redacted/projects/Better-Release-Radar/src/auth.ts:28:22)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Server.<anonymous> (/home/redacted/projects/Better-Release-Radar/src/auth.ts:93:9) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/redacted/projects/Better-Release-Radar/.cache/spotify_tokens.json'
```

**Comment by PaulMcInnis** [comment]
On this! thanks for the report

**Comment by PaulMcInnis** [comment]
Fixed!
