### ISSUE TITLE
Spotify API limitations

### ISSUE THREAD

**Issue by shillshocked** [PaulMcInnis/Better-Release-Radar#6]
I can get this to work to a certain level of completion, but it hasn't ever completed. I was using the older version for months with no issue. Here was my last attempt, it didn't go anywhere after getting the artists.

Below is the output:

`[destiny@godsbox Better-Release-Radar]$ npm start --max-age-days 17 --region ""

> better-release-radar@2.3.0 start
> NODE_OPTIONS='--no-warnings' ts-node ./src/main.ts 17 

[11-02 13:56] [INFO]: Using cached Spotify tokens.
[11-02 13:56] [INFO]: Starting Better Release Radar...
[11-02 13:56] [INFO]: Using cached Spotify tokens.
[11-02 13:56] [INFO]: Total followed artists: 9055
[11-02 13:58] [INFO]: Fetched and cached followed artists
[11-02 13:58] [INFO]: Fetching artists' albums...
 ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 0% | ETA: 0s | 0/15860[11-02 13:58] [ERROR]: Error fetching albums for artist 000DnGPNOsxvqb2YEHBePR [o]
[11-02 13:58] [INFO]: Error occurred, retrying after 0.5 seconds... (2 retries left)
[11-02 13:58] [ERROR]: Error fetching albums for artist 000DnGPNOsxvqb2YEHBePR [object Object]
[11-02 13:58] [INFO]: Error occurred, retrying after 1 seconds... (1 retries left)
[11-02 13:58] [ERROR]: Error fetching albums for artist 000DnGPNOsxvqb2YEHBePR [object Object]
[11-02 13:58] [ERROR]: Error fetching albums for artist 000DnGPNOsxvqb2YEHBePR: [object Object]
[11-02 13:58] [ERROR]: Error fetching albums for artist 000UmiuzgqlUjKHpvIWmAo [object Object]
[11-02 13:58] [INFO]: Error occurred, retrying after 0.5 seconds... (2 retries left)
[11-02 13:58] [ERROR]: Error fetching albums for artist 000UmiuzgqlUjKHpvIWmAo [object Object]
[11-02 13:58] [INFO]: Error occurred, retrying after 1 seconds... (1 retries left)
[11-02 13:58] [ERROR]: Error fetching albums for artist 000UmiuzgqlUjKHpvIWmAo [object Object]
[11-02 13:58] [ERROR]: Error fetching albums for artist 000UmiuzgqlUjKHpvIWmAo: [object Object]
[11-02 13:58] [ERROR]: Error fetching albums for artist 002hk7YmWcLHK83vzys8QE [object Object]
[11-02 13:58] [INFO]: Error occurred, retrying after 0.5 seconds... (2 retries left)
[11-02 13:58] [ERROR]: Error fetching albums for artist 002hk7YmWcLHK83vzys8QE [object Object]
[11-02 13:58] [INFO]: Error occurred, retrying after 1 seconds... (1 retries left)
[11-02 13:58] [ERROR]: Error fetching albums for artist 002hk7YmWcLHK83vzys8QE [object Object]
[11-02 13:58] [ERROR]: Error fetching albums for artist 002hk7YmWcLHK83vzys8QE: [object Object]
[11-02 13:58] [ERROR]: Error fetching albums for artist 0036LPMdeHuvvplfk77np9 [object Object]
[11-02 13:58] [INFO]: Error occurred, retrying after 0.5 seconds... (2 retries left)
[11-02 13:58] [ERROR]: Error fetching albums for artist 0036LPMdeHuvvplfk77np9 [object Object]
[11-02 13:58] [INFO]: Error occurred, retrying after 1 seconds... (1 retries left)
[11-02 13:58] [ERROR]: Error fetching albums for artist 0036LPMdeHuvvplfk77np9 [object Object]
[11-02 13:58] [ERROR]: Error fetching albums for artist 0036LPMdeHuvvplfk77np9: [object Object]
[11-02 13:58] [ERROR]: Error fetching albums for artist 009QwitRv9W2fiW2SzzG97 [object Object]
[11-02 13:58] [INFO]: Error occurred, retrying after 0.5 seconds... (2 retries left)
[11-02 13:58] [ERROR]: Error fetching albums for artist 009QwitRv9W2fiW2SzzG97 [object Object]
[11-02 13:58] [INFO]: Error occurred, retrying after 1 seconds... (1 retries left)
[11-02 13:58] [ERROR]: Error fetching albums for artist 009QwitRv9W2fiW2SzzG97 [object Object]
[11-02 13:58] [ERROR]: Error fetching albums for artist 009QwitRv9W2fiW2SzzG97: [object Object]
[11-02 13:58] [ERROR]: Error fetching albums for artist 00BAVwGA0NvXlLOx6N2pXk [object Object]
[11-02 13:58] [INFO]: Error occurred, retrying after 0.5 seconds... (2 retries left)
[11-02 13:58] [ERROR]: Error fetching albums for artist 00BAVwGA0NvXlLOx6N2pXk [object Object]
[11-02 13:58] [INFO]: Error occurred, retrying after 1 seconds... (1 retries left)
[11-02 13:58] [ERROR]: Error fetching albums for artist 00BAVwGA0NvXlLOx6N2pXk [object Object]
[11-02 13:58] [ERROR]: Error fetching albums for artist 00BAVwGA0NvXlLOx6N2pXk: [object Object]
[11-02 13:58] [ERROR]: Error fetching albums for artist 00CUTEhOVY9H6zJz7X23gL [object Object]
[11-02 13:58] [INFO]: Error occurred, retrying after 0.5 seconds... (2 retries left)
[11-02 13:58] [ERROR]: Error fetching albums for artist 00CUTEhOVY9H6zJz7X23gL [object Object]
[11-02 13:58] [INFO]: Error occurred, retrying after 1 seconds... (1 retries left)
[11-02 13:58] [ERROR]: Error fetching albums for artist 00CUTEhOVY9H6zJz7X23gL [object Object]
[11-02 13:58] [ERROR]: Error fetching albums for artist 00CUTEhOVY9H6zJz7X23gL: [object Object]
[11-02 13:58] [ERROR]: Error fetching albums for artist 00G5KYKo2LkMMWexylSL8H [object Object]
[11-02 13:58] [INFO]: Error occurred, retrying after 0.5 seconds... (2 retries left)
[11-02 13:58] [ERROR]: Error fetching albums for artist 00G5KYKo2LkMMWexylSL8H [object Object]
[11-02 13:58] [INFO]: Error occurred, retrying after 1 seconds... (1 retries left)
[11-02 13:58] [ERROR]: Error fetching albums for artist 00G5KYKo2LkMMWexylSL8H [object Object]
[11-02 13:58] [ERROR]: Error fetching albums for artist 00G5KYKo2LkMMWexylSL8H: [object Object]
[11-02 13:58] [ERROR]: Error fetching albums for artist 00OJ9bU7jc5Wd0hsqGNi3y [object Object]
[11-02 13:58] [INFO]: Error occurred, retrying after 0.5 seconds... (2 retries left)
[11-02 13:58] [ERROR]: Error fetching albums for artist 00OJ9bU7jc5Wd0hsqGNi3y [object Object]
[11-02 13:58] [INFO]: Error occurred, retrying after 1 seconds... (1 retries left)
[11-02 13:58] [ERROR]: Error fetching albums for artist 00OJ9bU7jc5Wd0hsqGNi3y [object Object]
[11-02 13:58] [ERROR]: Error fetching albums for artist 00OJ9bU7jc5Wd0hsqGNi3y: [object Object]
[11-02 13:58] [ERROR]: Error fetching albums for artist 00RLwL6cJGCVjp4juNrNok [object Object]
[11-02 13:58] [INFO]: Error occurred, retrying after 0.5 seconds... (2 retries left)
[11-02 13:58] [ERROR]: Error fetching albums for artist 00RLwL6cJGCVjp4juNrNok [object Object]
[11-02 13:58] [INFO]: Error occurred, retrying after 1 seconds... (1 retries left)
[11-02 13:58] [ERROR]: Error fetching albums for artist 00RLwL6cJGCVjp4juNrNok [object Object]
[11-02 13:58] [ERROR]: Error fetching albums for artist 00RLwL6cJGCVjp4juNrNok: [object Object]
[11-02 13:58] [ERROR]: Error fetching albums for artist 00T7vUxrsqmrjBusWzZqw3 [object Object]
[11-02 13:58] [INFO]: Error occurred, retrying after 0.5 seconds... (2 retries left)
[11-02 13:58] [ERROR]: Error fetching albums for artist 00T7vUxrsqmrjBusWzZqw3 [object Object]
[11-02 13:58] [INFO]: Error occurred, retrying after 1 seconds... (1 retries left)
[11-02 13:58] [ERROR]: Error fetching albums for artist 00T7vUxrsqmrjBusWzZqw3 [object Object]
[11-02 13:58] [ERROR]: Error fetching albums for artist 00T7vUxrsqmrjBusWzZqw3: [object Object]
[11-02 13:58] [ERROR]: Error fetching albums for artist 00TkLDqPqo5gb0sh8DGpCo [object Object]
[11-02 13:58] [INFO]: Error occurred, retrying after 0.5 seconds... (2 retries left)
[11-02 13:58] [ERROR]: Error fetching albums for artist 00TkLDqPqo5gb0sh8DGpCo [object Object]
[11-02 13:58] [INFO]: Error occurred, retrying after 1 seconds... (1 retries left)
[11-02 13:58] [ERROR]: Error fetching albums for artist 00TkLDqPqo5gb0sh8DGpCo [object Object]
[11-02 13:58] [ERROR]: Error fetching albums for artist 00TkLDqPqo5gb0sh8DGpCo: [object Object]
[11-02 13:58] [ERROR]: Error fetching albums for artist 00UgS2xUXMzwQPuHwCo2ec [object Object]
[11-02 13:58] [INFO]: Error occurred, retrying after 0.5 seconds... (2 retries left)
[11-02 13:58] [ERROR]: Error fetching albums for artist 00UgS2xUXMzwQPuHwCo2ec [object Object]
[11-02 13:58] [INFO]: Error occurred, retrying after 1 seconds... (1 retries left)
[11-02 13:58] [ERROR]: Error fetching albums for artist 00UgS2xUXMzwQPuHwCo2ec [object Object]
[11-02 13:58] [ERROR]: Error fetching albums for artist 00UgS2xUXMzwQPuHwCo2ec: [object Object]
[11-02 13:58] [ERROR]: Error fetching albums for artist 00ZfdcYfOCXeygtGhbvy4w [object Object]
[11-02 13:58] [INFO]: Error occurred, retrying after 0.5 seconds... (2 retries left)
[11-02 13:58] [ERROR]: Error fetching albums for artist 00ZfdcYfOCXeygtGhbvy4w [object Object]
[11-02 13:58] [INFO]: Error occurred, retrying after 1 seconds... (1 retries left)
[11-02 13:58] [ERROR]: Error fetching albums for artist 00ZfdcYfOCXeygtGhbvy4w [object Object]
[11-02 13:58] [ERROR]: Error fetching albums for artist 00ZfdcYfOCXeygtGhbvy4w: [object Object]
[11-02 13:58] [ERROR]: Error fetching albums for artist 00b8jKD6HWIqU7xeEGgoev [object Object]
[11-02 13:58] [INFO]: Error occurred, retrying after 0.5 seconds... (2 retries left)
[11-02 13:58] [ERROR]: Error fetching albums for artist 00b8jKD6HWIqU7xeEGgoev [object Object]
[11-02 13:58] [INFO]: Error occurred, retrying after 1 seconds... (1 retries left)
[11-02 13:58] [ERROR]: Error fetching albums for artist 00b8jKD6HWIqU7xeEGgoev [object Object]
[11-02 13:58] [ERROR]: Error fetching albums for artist 00b8jKD6HWIqU7xeEGgoev: [object Object]
[11-02 13:58] [ERROR]: Error fetching albums for artist 00pwtWmIogyWrDk66Zdj6X [object Object]
[11-02 13:58] [INFO]: Error occurred, retrying after 0.5 seconds... (2 retries left)
[11-02 13:58] [ERROR]: Error fetching albums for artist 00pwtWmIogyWrDk66Zdj6X [object Object]
[11-02 13:58] [INFO]: Error occurred, retrying after 1 seconds... (1 retries left)
[11-02 13:58] [ERROR]: Error fetching albums for artist 00pwtWmIogyWrDk66Zdj6X [object Object]
[11-02 13:58] [ERROR]: Error fetching albums for artist 00pwtWmIogyWrDk66Zdj6X: [object Object]
[11-02 13:58] [ERROR]: Error fetching albums for artist 00qLitXB14xc039nmJPa7M [object Object]
[11-02 13:58] [INFO]: Error occurred, retrying after 0.5 seconds... (2 retries left)
[11-02 13:58] [ERROR]: Error fetching albums for artist 00qLitXB14xc039nmJPa7M [object Object]
[11-02 13:58] [INFO]: Error occurred, retrying after 1 seconds... (1 retries left)
[11-02 13:58] [ERROR]: Error fetching albums for artist 00qLitXB14xc039nmJPa7M [object Object]
[11-02 13:58] [ERROR]: Error fetching albums for artist 00qLitXB14xc039nmJPa7M: [object Object]
[11-02 13:58] [ERROR]: Error fetching albums for artist 014t53wF0GoMOZGwGMq3nG [object Object]
[11-02 13:58] [INFO]: Error occurred, retrying after 0.5 seconds... (2 retries left)
[11-02 13:58] [ERROR]: Error fetching albums for artist 014t53wF0GoMOZGwGMq3nG [object Object]
[11-02 13:58] [INFO]: Error occurred, retrying after 1 seconds... (1 retries left)
[11-02 13:58] [ERROR]: Error fetching albums for artist 014t53wF0GoMOZGwGMq3nG [object Object]
[11-02 13:58] [ERROR]: Error fetching albums for artist 014t53wF0GoMOZGwGMq3nG: [object Object]
[11-02 13:58] [ERROR]: Error fetching albums for artist 01B2qqSPOJHxsIVs2dgTDH [object Object]
[11-02 13:58] [INFO]: Error occurred, retrying after 0.5 seconds... (2 retries left)
[11-02 13:58] [ERROR]: Error fetching albums for artist 01B2qqSPOJHxsIVs2dgTDH [object Object]
[11-02 13:58] [INFO]: Error occurred, retrying after 1 seconds... (1 retries left)
[11-02 13:58] [ERROR]: Error fetching albums for artist 01B2qqSPOJHxsIVs2dgTDH [object Object]
[11-02 13:58] [ERROR]: Error fetching albums for artist 01B2qqSPOJHxsIVs2dgTDH: [object Object]
[11-02 13:58] [ERROR]: Error fetching albums for artist 01B8pvlWIWBmkqMaAeeWXQ [object Object]
[11-02 13:58] [INFO]: Error occurred, retrying after 0.5 seconds... (2 retries left)
[11-02 13:58] [ERROR]: Error fetching albums for artist 01B8pvlWIWBmkqMaAeeWXQ [object Object]
[11-02 13:58] [INFO]: Error occurred, retrying after 1 seconds... (1 retries left)
[11-02 13:58] [ERROR]: Error fetching albums for artist 01B8pvlWIWBmkqMaAeeWXQ [object Object]
[11-02 13:58] [ERROR]: Error fetching albums for artist 01B8pvlWIWBmkqMaAeeWXQ: [object Object]
[11-02 13:58] [ERROR]: Error fetching albums for artist 01LL6jd9Q7W2ACHhrx6rBs [object Object]
[11-02 13:58] [INFO]: Error occurred, retrying after 0.5 seconds... (2 retries left)
[11-02 13:58] [ERROR]: Error fetching albums for artist 01LL6jd9Q7W2ACHhrx6rBs [object Object]
[11-02 13:58] [INFO]: Error occurred, retrying after 1 seconds... (1 retries left)

`

**Comment by PaulMcInnis** [comment]
Hmm ill try this out in a fresh env, maybe I've missed something here. 

can you confirm that install comes back w/o errors? 

Looks like I also need to log errors better.

**Comment by PaulMcInnis** [comment]
I wasn't able to replicate the issue you are seeing, can you https://github.com/PaulMcInnis/Better-Release-Radar/blob/6ced6c49be41a561bd482b9cb758516ba80bad85/src/fetch.ts#L93 change this to log err.message? 

I have a feeling that maybe there is some issue with a string for a specific artist or with auth.

https://github.com/PaulMcInnis/Better-Release-Radar/releases btw in the mean time you can still access the previous version here if you need it (v1.0)

Thanks for trying this out!

**Comment by shillshocked** [comment]
Sometimes I could get it to go to about 20-30% of albums fetched, and then it gets the errors. But lately I can't even get it to start to get that far. It is just stuck at:

"Total followed artists: 9055"

I tried deleting the cache and reauthorizing the token. I even resorted to deleting everything and reinstalling again. Still seems to get stuck there now.

**Comment by shillshocked** [comment]
Alright, tried that...got errors from the start lately:

[log.log](https://github.com/user-attachments/files/17686497/log.log)

**Comment by PaulMcInnis** [comment]
@shillshocked can you make the change there so I can see what the error is? it's logging out `[object, object]` so I cant actually see your error logged there

thanks!

**Comment by shillshocked** [comment]
I tried changing that line to err.message but it just gave an error and wouldn't start.

So I tried what I thought you meant rather than what you typed instead:

`logger.error( \`Error fetching albums for artist ${artistId}\`, err.message); `

and that is the log it produced.

I can't get github to output what I typed exactly because I cannot escape the backtick character consistently for some reason.

**Comment by PaulMcInnis** [comment]
Maybe we can try 

`JSON.stringify(err)`

or even just dumping that try/catch all together, I want to see the full error message in there 👀

**Comment by shillshocked** [comment]
I am going to test this out on my Windows device before I go any further with a fresh install. Let's see if I get a similar error. My guess is that because I have 9060 artists I am following, Spotify's API is limiting me at some point. I never had a problem with a similar amount of artists in the past, but that was before Spotify went all insane with their recent limitations.

**Comment by shillshocked** [comment]
Error on Windows too after 3036/9060 artists:

PS C:\Programs\Better-Release-Radar> $env:NODE_OPTIONS="--no-warnings"; npm start --max-age-days 1

> better-release-radar@2.3.0 start
> NODE_OPTIONS='--no-warnings' ts-node ./src/main.ts 1

'NODE_OPTIONS' is not recognized as an internal or external command,
operable program or batch file.
PS C:\Programs\Better-Release-Radar> npm start --max-age-days 1

> better-release-radar@2.3.0 start
> set NODE_OPTIONS=--no-warnings && ts-node ./src/main.ts 1 1

[12-18 17:26] [INFO]: Prompting user to authorize the app

  --------------------------------------------------
  Authorize your app by visiting this URL:
  https://accounts.spotify.com/authorize?client_id=64cd1081d5b14a23b12cbe563e0f02a1&response_type=code&redirect_uri=http://localhost:8888/callback&scope=user-follow-read&state=random-state
  --------------------------------------------------

[12-18 17:26] [INFO]: Listening for Spotify authorization code on http://localhost:8888/callback
[12-18 17:26] [INFO]: Waiting for authorization before running main...
[12-18 17:27] [INFO]: Authorization code received:
Error exchanging authorization code: Error: ENOENT: no such file or directory, open 'C:\Programs\Better-Release-Radar\.cache\spotify_tokens.json'
    at Object.writeFileSync (node:fs:2344:20)
    at saveTokensToCache (C:\Programs\Better-Release-Radar\src\cache.ts:30:6)
    at exchangeAuthorizationCode (C:\Programs\Better-Release-Radar\src\auth.ts:28:22)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Server.<anonymous> (C:\Programs\Better-Release-Radar\src\auth.ts:93:9) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Programs\\Better-Release-Radar\\.cache\\spotify_tokens.json'
}
[12-18 17:27] [INFO]: Starting Better Release Radar...
[12-18 17:27] [INFO]: Prompting user to authorize the app

  --------------------------------------------------
  Authorize your app by visiting this URL:
  https://accounts.spotify.com/authorize?client_id=64cd1081d5b14a23b12cbe563e0f02a1&response_type=code&redirect_uri=http://localhost:8888/callback&scope=user-follow-read&state=random-state
  --------------------------------------------------

[12-18 17:27] [INFO]: Listening for Spotify authorization code on http://localhost:8888/callback
[12-18 17:27] [INFO]: Total followed artists: 9060
[12-18 17:31] [INFO]: Fetched and cached followed artists
[12-18 17:31] [INFO]: Fetching artists' albums...
 █████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░ 33% | ETA: 10046s | 3036/9060[12-18 18:27] [ERROR]: Error fetching al.
Details: The access token expired.
[12-18 18:27] [INFO]: Access token expired. Refreshing token...
[12-18 18:27] [INFO]: Refreshing access token...
Error refreshing access token Error: Refresh token is missing from cache
    at refreshAccessToken (C:\Programs\Better-Release-Radar\src\auth.ts:41:13)
    at fetchArtistAlbumsWithRetry (C:\Programs\Better-Release-Radar\src\fetch.ts:119:33)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async scrape (C:\Programs\Better-Release-Radar\src\main.ts:87:28)
[12-18 18:27] [ERROR]: Error fetching albums for artist 6FpeJcIaVGY25QyAILB1rV An error occurred while communic.
Details: The access token expired.
[12-18 18:27] [INFO]: Access token expired. Refreshing token...
[12-18 18:27] [INFO]: Refreshing access token...
Error refreshing access token Error: Refresh token is missing from cache
    at refreshAccessToken (C:\Programs\Better-Release-Radar\src\auth.ts:41:13)
    at fetchArtistAlbumsWithRetry (C:\Programs\Better-Release-Radar\src\fetch.ts:119:33)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async scrape (C:\Programs\Better-Release-Radar\src\main.ts:87:28)
    
    (Error just repeats after that)

**Comment by shillshocked** [comment]
I can restart it and resume in Windows, with Linux it was corrupting and I had to start again from the beginning. I guess what is happening in Linux is that when it crashes, you get corruption that prevents resumption. Somehow Windows handles it better.

I wonder if the code needs to be modified to handle token expiration better?

Also coding in a stopping procedure that gracefully exits would be helpful.

**Comment by shillshocked** [comment]
After getting to about 40%, I hit the API limit apparently:

PS C:\Programs\Better-Release-Radar> npm start --max-age-days 1

> better-release-radar@2.3.0 start
> set NODE_OPTIONS=--no-warnings && ts-node ./src/main.ts 1 1

[12-18 18:30] [INFO]: Prompting user to authorize the app

  --------------------------------------------------
  Authorize your app by visiting this URL:
  https://accounts.spotify.com/authorize?client_id=64cd1081d5b14a23b12cbe563e0f02a1&response_type=code&redirect_uri=http://localhost:8888/callback&scope=user-follow-read&state=random-state
  --------------------------------------------------

[12-18 18:30] [INFO]: Listening for Spotify authorization code on http://localhost:8888/callback
[12-18 18:30] [INFO]: Waiting for authorization before running main...
[12-18 18:31] [INFO]: Authorization code received:
[12-18 18:31] [INFO]: Access token and refresh token set.
[12-18 18:31] [INFO]: Starting Better Release Radar...
[12-18 18:31] [INFO]: Using cached Spotify tokens.
[12-18 18:31] [INFO]: Loaded artists from cache: C:\Programs\Better-Release-Radar\.cache\followed_artists_2024-12-18.json
[12-18 18:31] [INFO]: Loaded albums from cache: C:\Programs\Better-Release-Radar\.cache\album_cache_2024-12-18.json
 ██████████████████░░░░░░░░░░░░░░░░░░░░░░ 44% | ETA: 10772s | 4031/9060[12-18 19:03] [ERROR]: Error fetching al]
[12-18 19:03] [INFO]: Error occurred, retrying after 0.5 seconds... (2 retries left)
[12-18 19:04] [ERROR]: Error fetching albums for artist 2p0Ijwq3ufXdca65KnK4Vq [object Object]
[12-18 19:04] [INFO]: Error occurred, retrying after 1 seconds... (1 retries left)
[12-18 19:04] [ERROR]: Error fetching albums for artist 2p0Ijwq3ufXdca65KnK4Vq [object Object]
[12-18 19:04] [ERROR]: Error fetching albums for artist 2p0Ijwq3ufXdca65KnK4Vq: [object Object]
[12-18 19:04] [ERROR]: Error fetching albums for artist 2tFxfxgcFdPIipKiDVZYyC [object Object]
[12-18 19:04] [INFO]: Error occurred, retrying after 0.5 seconds... (2 retries left)
[12-18 19:04] [ERROR]: Error fetching albums for artist 2tFxfxgcFdPIipKiDVZYyC [object Object]
[12-18 19:04] [INFO]: Error occurred, retrying after 1 seconds... (1 retries left)
[12-18 19:04] [ERROR]: Error fetching albums for artist 2tFxfxgcFdPIipKiDVZYyC [object Object]
[12-18 19:04] [ERROR]: Error fetching albums for artist 2tFxfxgcFdPIipKiDVZYyC: [object Object]
[12-18 19:04] [ERROR]: Error fetching albums for artist 2uodbv2953Z7R1ipwucK2A [object Object]
[12-18 19:04] [INFO]: Error occurred, retrying after 0.5 seconds... (2 retries left)
[12-18 19:04] [ERROR]: Error fetching albums for artist 2uodbv2953Z7R1ipwucK2A [object Object]
[12-18 19:04] [INFO]: Error occurred, retrying after 1 seconds... (1 retries left)
[12-18 19:04] [ERROR]: Error fetching albums for artist 2uodbv2953Z7R1ipwucK2A [object Object]
[12-18 19:04] [ERROR]: Error fetching albums for artist 2uodbv2953Z7R1ipwucK2A: [object Object]
[12-18 19:04] [ERROR]: Error fetching albums for artist 2upCjUln8IL42BzlfVLOCl [object Object]
[12-18 19:04] [INFO]: Error occurred, retrying after 0.5 seconds... (2 retries left)
[12-18 19:04] [ERROR]: Error fetching albums for artist 2upCjUln8IL42BzlfVLOCl [object Object]
[12-18 19:04] [INFO]: Error occurred, retrying after 1 seconds... (1 retries left)

**Comment by shillshocked** [comment]
I think in order to complete this process, I would need an extended API key...unfortunately I don't have an app that's worthy of public use yet. Other options include waiting a day to resume, or using an additional key.

**Comment by PaulMcInnis** [comment]
damn yeah looks like 9060 artists is a use case that is causing this issue. 

I think to be fair there are potentially more request efficient ways to do this - it is true that the old API was more lenient as well. 

will look into the resuming issue though, I think at the very least it would make sense to resume from where it left off either due to errors or rate limit (at least that was my intent)

**Comment by shillshocked** [comment]
Good stuff. Yeah, I actually just increased my followed artists to over 24,000 after I followed all the artists of my favorite genres. I am thinking about following my liked song artists and library added song/album artists as well, among others. :)

**Comment by shillshocked** [comment]
Curious, here was my latest result:

PS C:\Programs\Better-Release-Radar> npm start -- --max-age-days "" --region ""

> better-release-radar@2.3.0 start
> set NODE_OPTIONS=--no-warnings && ts-node ./src/main.ts 1

[12-23 14:24] [INFO]: Prompting user to authorize the app

  --------------------------------------------------
  Authorize your app by visiting this URL:
  https://accounts.spotify.com/authorize?client_id=EDITEDOUT&response_type=code&redirect_uri=http://localhost:8888/callback&scope=user-follow-read&state=random-state
  --------------------------------------------------

[12-23 14:24] [INFO]: Listening for Spotify authorization code on http://localhost:8888/callback
[12-23 14:24] [INFO]: Waiting for authorization before running main...
[12-23 14:24] [INFO]: Authorization code received:
Error exchanging authorization code: Error: ENOENT: no such file or directory, open 'C:\Programs\Better-Release-Radar\.cache\spotify_tokens.json'
    at Object.writeFileSync (node:fs:2344:20)
    at saveTokensToCache (C:\Programs\Better-Release-Radar\src\cache.ts:30:6)
    at exchangeAuthorizationCode (C:\Programs\Better-Release-Radar\src\auth.ts:28:22)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Server.<anonymous> (C:\Programs\Better-Release-Radar\src\auth.ts:93:9) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Programs\\Better-Release-Radar\\.cache\\spotify_tokens.json'
}
[12-23 14:24] [INFO]: Starting Better Release Radar...
[12-23 14:24] [INFO]: Prompting user to authorize the app

  --------------------------------------------------
  Authorize your app by visiting this URL:
  https://accounts.spotify.com/authorize?client_id=EDITEDOUT&response_type=code&redirect_uri=http://localhost:8888/callback&scope=user-follow-read&state=random-state
  --------------------------------------------------

[12-23 14:24] [INFO]: Listening for Spotify authorization code on http://localhost:8888/callback
[12-23 14:24] [INFO]: Total followed artists: 24170
[12-23 14:25] [ERROR]: Error fetching followed artists: An error occurred while communicating with Spotify's Web API.
Details: com.spotify.hermes.service.RequestTimeoutException: Request timed out: 0629eae592ad56-206bb0-225a-88ed-d88d1426. Host: 0a852b762a142a00000101f6000004c400000036.ip.gae2.spotify.net.:5700.
[12-23 14:25] [ERROR]: Error running the script: An error occurred while communicating with Spotify's Web API.
Details: com.spotify.hermes.service.RequestTimeoutException: Request timed out: 0629eae592ad56-206bb0-225a-88ed-d88d1426. Host: 0a852b762a142a00000101f6000004c400000036.ip.gae2.spotify.net.:5700.

**Comment by PaulMcInnis** [comment]
I've improved the fetching a bit using batching, so miiiight have more luck now @shillshocked

**Comment by shillshocked** [comment]
Thank you. I have created a modification of your work, that is a bit more functional for my purposes. I based it on your current code.
